services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cyberelk\BrofixWidget\:
    resource: '../Classes/*'

  dashboard.widget.Cyberelk.BrofixWidget.brofixwidget:
    class: 'Cyberelk\BrofixWidget\Widgets\BrofixWidget'
    arguments:
    tags:
      - name: dashboard.widget
        identifier: 'brofixwidget'
        groupNames: 'general'
        title: 'LLL:EXT:brofix_widget/Resources/Private/Language/locallang.xlf:widget.title'
        description: 'LLL:EXT:brofix_widget/Resources/Private/Language/locallang.xlf:widget.description'
        iconIdentifier: 'extension-brofix'
        height: 'medium'
        width: 'small'
