services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cyberelk\BrofixWidget\:
    resource: '../Classes/*'

  dashboard.widget.brofix:
    class: 'Cyberelk\BrofixWidget\Widgets\BrofixWidget'
    arguments:
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'brofix'
        groupNames: 'general'
        title: 'LLL:EXT:brofix_widget/Resources/Private/Language/locallang.xlf:widget.title'
        description: 'LLL:EXT:brofix_widget/Resources/Private/Language/locallang.xlf:widget.description'
        iconIdentifier: 'extension-brofix'
        height: 'medium'
        width: 'small'
